import type { Metadata } from 'next'

// Styles
import '@/app/globals.css'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <>
      {children}
    </>
  )
}
